---
# Surcharge du TP 02 : elements propres au patching Debian.
# Debian depose un fichier temoin quand un redemarrage est requis.
maj_commande_reboot: "/usr/bin/test -f /var/run/reboot-required"
maj_rc_reboot_requis: 0
