---
- name: Detruire les conteneurs de test
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Supprimer les conteneurs
      containers.podman.podman_container:
        name: "{{ item }}"
        state: absent
      loop: "{{ groups['molecule'] | default([]) }}"
