---
galaxy_info:
  role_name: semaphore
  namespace: formation
  author: Formation Ansible
  description: Installation de Semaphore UI edition Community
  license: MIT
  min_ansible_version: "2.16"
  platforms:
    - name: Debian
      versions:
        - trixie
dependencies: []
